AllCops:
  Exclude:
    - "db/**"
    - "db/migrate/**"
    - "config/**/*"
    - "lib/tasks/**"
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes